name: nymble_music_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # For app routing
  go_router: ^13.2.2
  font_awesome_flutter: ^10.7.0
  provider: ^6.1.2

  hive: ^2.2.3
  lottie: ^3.1.0
  firebase_core: ^2.28.0
  firebase_auth: ^4.19.0
  http: ^1.2.1
  cloud_firestore: ^4.16.0
  connectivity_plus: ^6.0.1
  audioplayers: ^6.0.0
  hive_flutter: ^1.1.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  hive_generator: ^2.0.1
  build_runner: ^2.4.9

  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/dataJsons/
    - assets/music.mp3

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
